{% set name = "bitstruct" %}
{% set version = "8.13.0" %}
{% set sha256 = "7b87d9e41ff552a8cae06ea2368c3772b6f3102bdab4b65e793be7590d69f03b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bitstruct

about:
  home: https://github.com/eerimoq/bitstruct
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bit pack/unpack package.
  description: |
    This module is intended to have a similar interface as the python struct module, 
    but working on bits instead of primitive data types (char, int, ...).
  doc_url: http://bitstruct.readthedocs.io/en/latest/
  dev_url: https://github.com/eerimoq/bitstruct

extra:
  recipe-maintainers:
    - eerimoq
    - danielhrisca
