{% set name = "bitstruct" %}
{% set version = "8.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff0be4968a45caf8688e075f55cca7a3fe9212b069ba67e5b27b0926a11948ac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - bitstruct

about:
  home: https://github.com/eerimoq/bitstruct
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bit pack/unpack package.
  description: |
    This module is intended to have a similar interface as the python struct module, 
    but working on bits instead of primitive data types (char, int, ...).
  doc_url: http://bitstruct.readthedocs.io/en/latest/
  dev_url: https://github.com/eerimoq/bitstruct

extra:
  recipe-maintainers:
    - eerimoq
    - danielhrisca
